-- ----------------------------------------------------------------------------
PRINT '[STATEMENT GROUP A]'
CHECKPOINT; DBCC DROPCLEANBUFFERS; DBCC FREEPROCCACHE
DECLARE @d1 DATETIME = GETDATE();
	--
	-- WRITE STATEMENT GROUP A HERE
	--
WAITFOR DELAY '00:00:00.001'
PRINT 'elapsed time=' + CONVERT(VARCHAR(10), DATEDIFF(MILLISECOND, @D1, GETDATE()));
GO 3 -- INCREASE THE COUNTER TO RUN MULTIPLE TIMES

-- ----------------------------------------------------------------------------
PRINT '[STATEMENT GROUP B]'
CHECKPOINT; DBCC DROPCLEANBUFFERS; DBCC FREEPROCCACHE
DECLARE @d1 DATETIME = GETDATE();
	--
	-- WRITE STATEMENT GROUP B HERE
	--
WAITFOR DELAY '00:00:00.001'
PRINT 'elapsed time=' + CONVERT(VARCHAR(10), DATEDIFF(MILLISECOND, @D1, GETDATE()));
GO 3 -- INCREASE THE COUNTER TO RUN MULTIPLE TIMES
